debug: false
server:
  port: 8088
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
web3j:
  client-address: http://localhost:7545
  admin-client: true
amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: AKIAXQQ7WMZVIRQUKJ4R
  secretKey: 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
  bucketName: idhub-did-plus
orderbook:
  url: http://localhost:8080