debug: false
server:
  port: 8080
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
web3j:
  client-address: http://localhost:7545
  admin-client: true
amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: 
  secretKey: 
  bucketName: 