debug: true
server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb+srv://baiyuqi:byq2218283@cluster0-4bfkb.gcp.mongodb.net/test?retryWrites=true&w=majority
web3j:
  client-address: http://localhost:7545
  admin-client: true