debug: false
server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://readWriteDidPlusTest:IDHubreadWriteDidPlusTest@18.140.101.226,18.140.76.46,18.136.252.105/MagicRepository?connect=replicaSet;replicaSet=IDHub
web3j:
  client-address: http://localhost:7545
  admin-client: true
amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: AKIAXQQ7WMZVIRQUKJ4R
  secretKey: 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
  bucketName: idhub-did-plus