debug: false
server:
  port: 8080
spring:
  logging.level.org.springframework.boot.autoconfigure: ERROR
  data:
    mongodb:
      uri: mongodb+srv://baiyuqi:byq2218283@cluster0-4bfkb.gcp.mongodb.net/test?retryWrites=true&w=majority
      max-connection-idle-time: 60000
      keepAlive: 100
      connectTimeoutMS: 30000
      ssl-enabled: true
web3j:
  client-address: http://localhost:7545
  admin-client: true
amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: XXXXXXXXXXXXXXXXX
  secretKey: XXXXXXXXXXXXXXXXXXXXXXXXXX
  bucketName: your-bucket-name